language: php

php:
  - '7.0'
  - '7.1'

before_script:
  - composer install

script:
  - docker run -v $PWD:/app phpqa/php-cs-fixer fix --show-progress=estimating --verbose .
  - docker run -v $PWD:/app phpqa/security-checker security:check
#  - docker run -v $PWD:/app phpqa/phpcs .

notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: heroku
  api_key:
    secure: "9589c25b-ef12-438f-8ab6-712594e973b0"
  app: animalepik
  on:
    repo: Matthieu972/AnimalEpik
    branch: master