<?php

namespace AppBundle\Repository;

/**
 * ConveyanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConveyanceRepository extends \Doctrine\ORM\EntityRepository
{
}
